name: konsi_challenge
description: "Konsi Challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection:
  go_router: ^14.6.0
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  equatable: ^2.0.5
  get_it: ^8.0.2
  result_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
